# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /sps/nusol/qriffard/Aris/parisana

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /sps/nusol/qriffard/Aris/parisana

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /sps/nusol/qriffard/Aris/parisana/CMakeFiles /sps/nusol/qriffard/Aris/parisana/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /sps/nusol/qriffard/Aris/parisana/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LibDict

# Build rule for target.
LibDict: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LibDict
.PHONY : LibDict

# fast build rule for target.
LibDict/fast:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/build
.PHONY : LibDict/fast

#=============================================================================
# Target rules for targets named eventviewer.bin

# Build rule for target.
eventviewer.bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eventviewer.bin
.PHONY : eventviewer.bin

# fast build rule for target.
eventviewer.bin/fast:
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/build
.PHONY : eventviewer.bin/fast

#=============================================================================
# Target rules for targets named tpcanalysis.bin

# Build rule for target.
tpcanalysis.bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tpcanalysis.bin
.PHONY : tpcanalysis.bin

# fast build rule for target.
tpcanalysis.bin/fast:
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/build
.PHONY : tpcanalysis.bin/fast

LibDict.o: LibDict.cxx.o
.PHONY : LibDict.o

# target to build an object file
LibDict.cxx.o:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/LibDict.cxx.o
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/LibDict.cxx.o
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/LibDict.cxx.o
.PHONY : LibDict.cxx.o

LibDict.i: LibDict.cxx.i
.PHONY : LibDict.i

# target to preprocess a source file
LibDict.cxx.i:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/LibDict.cxx.i
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/LibDict.cxx.i
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/LibDict.cxx.i
.PHONY : LibDict.cxx.i

LibDict.s: LibDict.cxx.s
.PHONY : LibDict.s

# target to generate assembly for a file
LibDict.cxx.s:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/LibDict.cxx.s
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/LibDict.cxx.s
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/LibDict.cxx.s
.PHONY : LibDict.cxx.s

eventviewer.o: eventviewer.cc.o
.PHONY : eventviewer.o

# target to build an object file
eventviewer.cc.o:
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/eventviewer.cc.o
.PHONY : eventviewer.cc.o

eventviewer.i: eventviewer.cc.i
.PHONY : eventviewer.i

# target to preprocess a source file
eventviewer.cc.i:
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/eventviewer.cc.i
.PHONY : eventviewer.cc.i

eventviewer.s: eventviewer.cc.s
.PHONY : eventviewer.s

# target to generate assembly for a file
eventviewer.cc.s:
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/eventviewer.cc.s
.PHONY : eventviewer.cc.s

src/AverageWaveforms.o: src/AverageWaveforms.cc.o
.PHONY : src/AverageWaveforms.o

# target to build an object file
src/AverageWaveforms.cc.o:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/AverageWaveforms.cc.o
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/AverageWaveforms.cc.o
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/AverageWaveforms.cc.o
.PHONY : src/AverageWaveforms.cc.o

src/AverageWaveforms.i: src/AverageWaveforms.cc.i
.PHONY : src/AverageWaveforms.i

# target to preprocess a source file
src/AverageWaveforms.cc.i:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/AverageWaveforms.cc.i
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/AverageWaveforms.cc.i
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/AverageWaveforms.cc.i
.PHONY : src/AverageWaveforms.cc.i

src/AverageWaveforms.s: src/AverageWaveforms.cc.s
.PHONY : src/AverageWaveforms.s

# target to generate assembly for a file
src/AverageWaveforms.cc.s:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/AverageWaveforms.cc.s
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/AverageWaveforms.cc.s
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/AverageWaveforms.cc.s
.PHONY : src/AverageWaveforms.cc.s

src/BaselineFinder.o: src/BaselineFinder.cc.o
.PHONY : src/BaselineFinder.o

# target to build an object file
src/BaselineFinder.cc.o:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/BaselineFinder.cc.o
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/BaselineFinder.cc.o
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/BaselineFinder.cc.o
.PHONY : src/BaselineFinder.cc.o

src/BaselineFinder.i: src/BaselineFinder.cc.i
.PHONY : src/BaselineFinder.i

# target to preprocess a source file
src/BaselineFinder.cc.i:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/BaselineFinder.cc.i
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/BaselineFinder.cc.i
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/BaselineFinder.cc.i
.PHONY : src/BaselineFinder.cc.i

src/BaselineFinder.s: src/BaselineFinder.cc.s
.PHONY : src/BaselineFinder.s

# target to generate assembly for a file
src/BaselineFinder.cc.s:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/BaselineFinder.cc.s
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/BaselineFinder.cc.s
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/BaselineFinder.cc.s
.PHONY : src/BaselineFinder.cc.s

src/ChannelData.o: src/ChannelData.cc.o
.PHONY : src/ChannelData.o

# target to build an object file
src/ChannelData.cc.o:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/ChannelData.cc.o
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/ChannelData.cc.o
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/ChannelData.cc.o
.PHONY : src/ChannelData.cc.o

src/ChannelData.i: src/ChannelData.cc.i
.PHONY : src/ChannelData.i

# target to preprocess a source file
src/ChannelData.cc.i:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/ChannelData.cc.i
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/ChannelData.cc.i
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/ChannelData.cc.i
.PHONY : src/ChannelData.cc.i

src/ChannelData.s: src/ChannelData.cc.s
.PHONY : src/ChannelData.s

# target to generate assembly for a file
src/ChannelData.cc.s:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/ChannelData.cc.s
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/ChannelData.cc.s
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/ChannelData.cc.s
.PHONY : src/ChannelData.cc.s

src/Converter.o: src/Converter.cc.o
.PHONY : src/Converter.o

# target to build an object file
src/Converter.cc.o:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/Converter.cc.o
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/Converter.cc.o
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/Converter.cc.o
.PHONY : src/Converter.cc.o

src/Converter.i: src/Converter.cc.i
.PHONY : src/Converter.i

# target to preprocess a source file
src/Converter.cc.i:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/Converter.cc.i
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/Converter.cc.i
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/Converter.cc.i
.PHONY : src/Converter.cc.i

src/Converter.s: src/Converter.cc.s
.PHONY : src/Converter.s

# target to generate assembly for a file
src/Converter.cc.s:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/Converter.cc.s
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/Converter.cc.s
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/Converter.cc.s
.PHONY : src/Converter.cc.s

src/EventData.o: src/EventData.cc.o
.PHONY : src/EventData.o

# target to build an object file
src/EventData.cc.o:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/EventData.cc.o
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/EventData.cc.o
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/EventData.cc.o
.PHONY : src/EventData.cc.o

src/EventData.i: src/EventData.cc.i
.PHONY : src/EventData.i

# target to preprocess a source file
src/EventData.cc.i:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/EventData.cc.i
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/EventData.cc.i
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/EventData.cc.i
.PHONY : src/EventData.cc.i

src/EventData.s: src/EventData.cc.s
.PHONY : src/EventData.s

# target to generate assembly for a file
src/EventData.cc.s:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/EventData.cc.s
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/EventData.cc.s
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/EventData.cc.s
.PHONY : src/EventData.cc.s

src/EventNavigator.o: src/EventNavigator.cc.o
.PHONY : src/EventNavigator.o

# target to build an object file
src/EventNavigator.cc.o:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/EventNavigator.cc.o
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/EventNavigator.cc.o
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/EventNavigator.cc.o
.PHONY : src/EventNavigator.cc.o

src/EventNavigator.i: src/EventNavigator.cc.i
.PHONY : src/EventNavigator.i

# target to preprocess a source file
src/EventNavigator.cc.i:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/EventNavigator.cc.i
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/EventNavigator.cc.i
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/EventNavigator.cc.i
.PHONY : src/EventNavigator.cc.i

src/EventNavigator.s: src/EventNavigator.cc.s
.PHONY : src/EventNavigator.s

# target to generate assembly for a file
src/EventNavigator.cc.s:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/EventNavigator.cc.s
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/EventNavigator.cc.s
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/EventNavigator.cc.s
.PHONY : src/EventNavigator.cc.s

src/EventProcessor.o: src/EventProcessor.cc.o
.PHONY : src/EventProcessor.o

# target to build an object file
src/EventProcessor.cc.o:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/EventProcessor.cc.o
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/EventProcessor.cc.o
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/EventProcessor.cc.o
.PHONY : src/EventProcessor.cc.o

src/EventProcessor.i: src/EventProcessor.cc.i
.PHONY : src/EventProcessor.i

# target to preprocess a source file
src/EventProcessor.cc.i:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/EventProcessor.cc.i
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/EventProcessor.cc.i
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/EventProcessor.cc.i
.PHONY : src/EventProcessor.cc.i

src/EventProcessor.s: src/EventProcessor.cc.s
.PHONY : src/EventProcessor.s

# target to generate assembly for a file
src/EventProcessor.cc.s:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/EventProcessor.cc.s
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/EventProcessor.cc.s
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/EventProcessor.cc.s
.PHONY : src/EventProcessor.cc.s

src/FFT.o: src/FFT.cc.o
.PHONY : src/FFT.o

# target to build an object file
src/FFT.cc.o:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/FFT.cc.o
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/FFT.cc.o
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/FFT.cc.o
.PHONY : src/FFT.cc.o

src/FFT.i: src/FFT.cc.i
.PHONY : src/FFT.i

# target to preprocess a source file
src/FFT.cc.i:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/FFT.cc.i
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/FFT.cc.i
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/FFT.cc.i
.PHONY : src/FFT.cc.i

src/FFT.s: src/FFT.cc.s
.PHONY : src/FFT.s

# target to generate assembly for a file
src/FFT.cc.s:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/FFT.cc.s
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/FFT.cc.s
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/FFT.cc.s
.PHONY : src/FFT.cc.s

src/Integrator.o: src/Integrator.cc.o
.PHONY : src/Integrator.o

# target to build an object file
src/Integrator.cc.o:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/Integrator.cc.o
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/Integrator.cc.o
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/Integrator.cc.o
.PHONY : src/Integrator.cc.o

src/Integrator.i: src/Integrator.cc.i
.PHONY : src/Integrator.i

# target to preprocess a source file
src/Integrator.cc.i:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/Integrator.cc.i
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/Integrator.cc.i
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/Integrator.cc.i
.PHONY : src/Integrator.cc.i

src/Integrator.s: src/Integrator.cc.s
.PHONY : src/Integrator.s

# target to generate assembly for a file
src/Integrator.cc.s:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/Integrator.cc.s
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/Integrator.cc.s
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/Integrator.cc.s
.PHONY : src/Integrator.cc.s

src/LVDAQHeader.o: src/LVDAQHeader.cc.o
.PHONY : src/LVDAQHeader.o

# target to build an object file
src/LVDAQHeader.cc.o:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/LVDAQHeader.cc.o
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/LVDAQHeader.cc.o
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/LVDAQHeader.cc.o
.PHONY : src/LVDAQHeader.cc.o

src/LVDAQHeader.i: src/LVDAQHeader.cc.i
.PHONY : src/LVDAQHeader.i

# target to preprocess a source file
src/LVDAQHeader.cc.i:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/LVDAQHeader.cc.i
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/LVDAQHeader.cc.i
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/LVDAQHeader.cc.i
.PHONY : src/LVDAQHeader.cc.i

src/LVDAQHeader.s: src/LVDAQHeader.cc.s
.PHONY : src/LVDAQHeader.s

# target to generate assembly for a file
src/LVDAQHeader.cc.s:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/LVDAQHeader.cc.s
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/LVDAQHeader.cc.s
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/LVDAQHeader.cc.s
.PHONY : src/LVDAQHeader.cc.s

src/Module.o: src/Module.cc.o
.PHONY : src/Module.o

# target to build an object file
src/Module.cc.o:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/Module.cc.o
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/Module.cc.o
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/Module.cc.o
.PHONY : src/Module.cc.o

src/Module.i: src/Module.cc.i
.PHONY : src/Module.i

# target to preprocess a source file
src/Module.cc.i:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/Module.cc.i
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/Module.cc.i
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/Module.cc.i
.PHONY : src/Module.cc.i

src/Module.s: src/Module.cc.s
.PHONY : src/Module.s

# target to generate assembly for a file
src/Module.cc.s:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/Module.cc.s
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/Module.cc.s
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/Module.cc.s
.PHONY : src/Module.cc.s

src/ProcessedPlotter.o: src/ProcessedPlotter.cc.o
.PHONY : src/ProcessedPlotter.o

# target to build an object file
src/ProcessedPlotter.cc.o:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/ProcessedPlotter.cc.o
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/ProcessedPlotter.cc.o
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/ProcessedPlotter.cc.o
.PHONY : src/ProcessedPlotter.cc.o

src/ProcessedPlotter.i: src/ProcessedPlotter.cc.i
.PHONY : src/ProcessedPlotter.i

# target to preprocess a source file
src/ProcessedPlotter.cc.i:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/ProcessedPlotter.cc.i
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/ProcessedPlotter.cc.i
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/ProcessedPlotter.cc.i
.PHONY : src/ProcessedPlotter.cc.i

src/ProcessedPlotter.s: src/ProcessedPlotter.cc.s
.PHONY : src/ProcessedPlotter.s

# target to generate assembly for a file
src/ProcessedPlotter.cc.s:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/ProcessedPlotter.cc.s
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/ProcessedPlotter.cc.s
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/ProcessedPlotter.cc.s
.PHONY : src/ProcessedPlotter.cc.s

src/PulseData.o: src/PulseData.cc.o
.PHONY : src/PulseData.o

# target to build an object file
src/PulseData.cc.o:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/PulseData.cc.o
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/PulseData.cc.o
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/PulseData.cc.o
.PHONY : src/PulseData.cc.o

src/PulseData.i: src/PulseData.cc.i
.PHONY : src/PulseData.i

# target to preprocess a source file
src/PulseData.cc.i:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/PulseData.cc.i
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/PulseData.cc.i
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/PulseData.cc.i
.PHONY : src/PulseData.cc.i

src/PulseData.s: src/PulseData.cc.s
.PHONY : src/PulseData.s

# target to generate assembly for a file
src/PulseData.cc.s:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/PulseData.cc.s
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/PulseData.cc.s
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/PulseData.cc.s
.PHONY : src/PulseData.cc.s

src/PulseFinder.o: src/PulseFinder.cc.o
.PHONY : src/PulseFinder.o

# target to build an object file
src/PulseFinder.cc.o:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/PulseFinder.cc.o
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/PulseFinder.cc.o
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/PulseFinder.cc.o
.PHONY : src/PulseFinder.cc.o

src/PulseFinder.i: src/PulseFinder.cc.i
.PHONY : src/PulseFinder.i

# target to preprocess a source file
src/PulseFinder.cc.i:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/PulseFinder.cc.i
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/PulseFinder.cc.i
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/PulseFinder.cc.i
.PHONY : src/PulseFinder.cc.i

src/PulseFinder.s: src/PulseFinder.cc.s
.PHONY : src/PulseFinder.s

# target to generate assembly for a file
src/PulseFinder.cc.s:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/PulseFinder.cc.s
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/PulseFinder.cc.s
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/PulseFinder.cc.s
.PHONY : src/PulseFinder.cc.s

src/ROI.o: src/ROI.cc.o
.PHONY : src/ROI.o

# target to build an object file
src/ROI.cc.o:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/ROI.cc.o
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/ROI.cc.o
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/ROI.cc.o
.PHONY : src/ROI.cc.o

src/ROI.i: src/ROI.cc.i
.PHONY : src/ROI.i

# target to preprocess a source file
src/ROI.cc.i:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/ROI.cc.i
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/ROI.cc.i
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/ROI.cc.i
.PHONY : src/ROI.cc.i

src/ROI.s: src/ROI.cc.s
.PHONY : src/ROI.s

# target to generate assembly for a file
src/ROI.cc.s:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/ROI.cc.s
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/ROI.cc.s
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/ROI.cc.s
.PHONY : src/ROI.cc.s

src/SumChannel.o: src/SumChannel.cc.o
.PHONY : src/SumChannel.o

# target to build an object file
src/SumChannel.cc.o:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/SumChannel.cc.o
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/SumChannel.cc.o
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/SumChannel.cc.o
.PHONY : src/SumChannel.cc.o

src/SumChannel.i: src/SumChannel.cc.i
.PHONY : src/SumChannel.i

# target to preprocess a source file
src/SumChannel.cc.i:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/SumChannel.cc.i
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/SumChannel.cc.i
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/SumChannel.cc.i
.PHONY : src/SumChannel.cc.i

src/SumChannel.s: src/SumChannel.cc.s
.PHONY : src/SumChannel.s

# target to generate assembly for a file
src/SumChannel.cc.s:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/SumChannel.cc.s
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/SumChannel.cc.s
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/SumChannel.cc.s
.PHONY : src/SumChannel.cc.s

src/ZeroSuppressor.o: src/ZeroSuppressor.cc.o
.PHONY : src/ZeroSuppressor.o

# target to build an object file
src/ZeroSuppressor.cc.o:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/ZeroSuppressor.cc.o
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/ZeroSuppressor.cc.o
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/ZeroSuppressor.cc.o
.PHONY : src/ZeroSuppressor.cc.o

src/ZeroSuppressor.i: src/ZeroSuppressor.cc.i
.PHONY : src/ZeroSuppressor.i

# target to preprocess a source file
src/ZeroSuppressor.cc.i:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/ZeroSuppressor.cc.i
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/ZeroSuppressor.cc.i
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/ZeroSuppressor.cc.i
.PHONY : src/ZeroSuppressor.cc.i

src/ZeroSuppressor.s: src/ZeroSuppressor.cc.s
.PHONY : src/ZeroSuppressor.s

# target to generate assembly for a file
src/ZeroSuppressor.cc.s:
	$(MAKE) -f CMakeFiles/LibDict.dir/build.make CMakeFiles/LibDict.dir/src/ZeroSuppressor.cc.s
	$(MAKE) -f CMakeFiles/eventviewer.bin.dir/build.make CMakeFiles/eventviewer.bin.dir/src/ZeroSuppressor.cc.s
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/src/ZeroSuppressor.cc.s
.PHONY : src/ZeroSuppressor.cc.s

tpcanalysis.o: tpcanalysis.cc.o
.PHONY : tpcanalysis.o

# target to build an object file
tpcanalysis.cc.o:
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/tpcanalysis.cc.o
.PHONY : tpcanalysis.cc.o

tpcanalysis.i: tpcanalysis.cc.i
.PHONY : tpcanalysis.i

# target to preprocess a source file
tpcanalysis.cc.i:
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/tpcanalysis.cc.i
.PHONY : tpcanalysis.cc.i

tpcanalysis.s: tpcanalysis.cc.s
.PHONY : tpcanalysis.s

# target to generate assembly for a file
tpcanalysis.cc.s:
	$(MAKE) -f CMakeFiles/tpcanalysis.bin.dir/build.make CMakeFiles/tpcanalysis.bin.dir/tpcanalysis.cc.s
.PHONY : tpcanalysis.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... LibDict"
	@echo "... edit_cache"
	@echo "... eventviewer.bin"
	@echo "... rebuild_cache"
	@echo "... tpcanalysis.bin"
	@echo "... LibDict.o"
	@echo "... LibDict.i"
	@echo "... LibDict.s"
	@echo "... eventviewer.o"
	@echo "... eventviewer.i"
	@echo "... eventviewer.s"
	@echo "... src/AverageWaveforms.o"
	@echo "... src/AverageWaveforms.i"
	@echo "... src/AverageWaveforms.s"
	@echo "... src/BaselineFinder.o"
	@echo "... src/BaselineFinder.i"
	@echo "... src/BaselineFinder.s"
	@echo "... src/ChannelData.o"
	@echo "... src/ChannelData.i"
	@echo "... src/ChannelData.s"
	@echo "... src/Converter.o"
	@echo "... src/Converter.i"
	@echo "... src/Converter.s"
	@echo "... src/EventData.o"
	@echo "... src/EventData.i"
	@echo "... src/EventData.s"
	@echo "... src/EventNavigator.o"
	@echo "... src/EventNavigator.i"
	@echo "... src/EventNavigator.s"
	@echo "... src/EventProcessor.o"
	@echo "... src/EventProcessor.i"
	@echo "... src/EventProcessor.s"
	@echo "... src/FFT.o"
	@echo "... src/FFT.i"
	@echo "... src/FFT.s"
	@echo "... src/Integrator.o"
	@echo "... src/Integrator.i"
	@echo "... src/Integrator.s"
	@echo "... src/LVDAQHeader.o"
	@echo "... src/LVDAQHeader.i"
	@echo "... src/LVDAQHeader.s"
	@echo "... src/Module.o"
	@echo "... src/Module.i"
	@echo "... src/Module.s"
	@echo "... src/ProcessedPlotter.o"
	@echo "... src/ProcessedPlotter.i"
	@echo "... src/ProcessedPlotter.s"
	@echo "... src/PulseData.o"
	@echo "... src/PulseData.i"
	@echo "... src/PulseData.s"
	@echo "... src/PulseFinder.o"
	@echo "... src/PulseFinder.i"
	@echo "... src/PulseFinder.s"
	@echo "... src/ROI.o"
	@echo "... src/ROI.i"
	@echo "... src/ROI.s"
	@echo "... src/SumChannel.o"
	@echo "... src/SumChannel.i"
	@echo "... src/SumChannel.s"
	@echo "... src/ZeroSuppressor.o"
	@echo "... src/ZeroSuppressor.i"
	@echo "... src/ZeroSuppressor.s"
	@echo "... tpcanalysis.o"
	@echo "... tpcanalysis.i"
	@echo "... tpcanalysis.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

